/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TourMaker;

import TourMaker.gui.CreateProject;
import TourMaker.gui.MainScreen;
import javax.swing.JDialog;
import javax.swing.UIManager;

public class App {

  public static void main(String[] args) {
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
    }
    MainScreen.getInstance();
  }
}
